### ISSUE TITLE
environment can override stack values

### ISSUE THREAD

**Issue by atward** [delfick/bespin#34]
User story: Be able to define a set of tags and use them throughout the configuration.
It is a common use case for organisations to define a tagging standard and require that tags are applied to all resources.
Initial implementation from user is to use yaml aliases on mappings (eg: `common_tags: &tags`) however this is only valid within a single file.

Propose extending `Environment` to include `tags` and have that merged over the top of `Stack.tags`. 

Raising this issue to solicit design feedback.

**Comment by atward** [comment]
Seems like this is already supported by bespin.collector converter ([bespin/collector.py#L177](https://github.com/delfick/bespin/blob/e80aa02797d328be3d1daf78dd14cc4ab093d95c/bespin/collector.py#L177))

Suggest updating docs to include details/examples.

**Comment by delfick** [comment]
are you able to try it and see if that works, afaict it'll actually ignore tags if you define it in the environment because https://github.com/delfick/bespin/blob/master/bespin/option_spec/bespin_specs.py#L180 doesn't know about tags.

(that spec is installed on the configuration here https://github.com/delfick/bespin/blob/master/bespin/collector.py#L135)

**Comment by atward** [comment]
does not care
```
---
environments:
  poc:
    tags:
      tag_at_env: env_override
      environment: "{environment}"
    cruft: that no one should care about

stacks:
  a:
    stack_yaml: "{config_root}/user.yaml"
    stack_policy: "{config_root}/stack_policy.json"
    params_yaml: {}

    tags:
      tags_at_stack: stack

    poc:
      tags:
        tag_env_override: stack_env_override
```

```
$ bespin deploy poc a 2>/dev/null && aws cloudformation describe-stacks --stack a --query 'Stacks[].Tags' --output text
Building - a
[]
environment	poc
tags_at_stack	stack
tag_at_env	env_override
tag_env_override	stack_env_override
```

**Comment by delfick** [comment]
cool,

I think I see why too.

The converter is put onto the environments key, whereas the stack spec gets the particular environment that should be used, so nothing converts it.....

**Comment by atward** [comment]
This hole might be nice to fix to prevent pebkac.

I did something like:

```
---
environments:
  poc:
    stack_name: foo
```

and got the expected
```
14:32:55 INFO    bespin.amazon.cloudformation Using region [ap-southeast-2] for cloudformation (foo)
14:32:56 ERROR   bespin.amazon.mixin Couldn't find stack -(400)- Stack with id foo does not exist
```
